name: raven
description: "News aggregator"
publish_to: 'none'

version: 0.14.0+216

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  dart_rss: ^3.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_smart_retry: ^6.0.0
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter

  flutter_html: ^3.0.0-beta.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  html: ^0.15.4
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  share_plus: ^9.0.0
  url_launcher: ^6.2.6
  worker_manager: ^7.0.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  lints: ^4.0.0
  test: ^1.25.5

flutter:
  uses-material-design: true
